export enum ActionType {
    MOVE_NOTE = 'MOVE_NOTE',
    DELETE_NOTE = 'DELETE_NOTE',
    INSERT_NOTE_AFTER = 'INSERT_NOTE_AFTER',
    UPDATE_NOTE = 'UPDATE_NOTE',
    FETCH_NOTES = 'FETCH_NOTES',
    FETCH_NOTES_COMPLETE = 'FETCH_NOTES_COMPLETE',
    FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR',
    SAVE_NOTES_ERROR = 'SAVE_NOTES_ERROR',
}
